### PR TITLE
im stupid.

### PR DESCRIPTION
**Pull request by ghost**
im a dumbass.

### CODE REVIEW

**Comment by ghost** [comment]
Lmao, why you don't want add this to plugin bro?

**Comment by OGFris** [comment]
because it will not work, the key is checked on the server side smh it will just create a bug

**Comment by NycuRO** [comment]
@OGFris I use and it work lmao

**Comment by ghost** [comment]
And why the hell use your website when i can use other site instanceof yours?

sorry im stupid.

**Comment by yesitswalid** [comment]
Please stop spam.

**Comment by OGFris** [comment]
@NycuRO smh you're stupid i swear, please read the description before saying any other bullshits, i made my own ProxyChecker free, you can check how many times you want for free but if you want to check other ports than the default ones you can buy the premium and everytime you send a request if the default ports doesn't seem like a proxy a background process will start to check every port to make sure that next time you'll catch it.

**Comment by OGFris** [comment]
@NycuRO "And why the hell use your website when i can use other site instanceof yours?" fucking dumbass just use the other sites that allow only 50 requests per minute and stop saying dumb shit about other people's work if you can't do better.

**Comment by NycuRO** [comment]
lmao, you stupid

**Comment by yesitswalid** [comment]
Stop Insults please, calm down what is your problem ?

**Pull request closed without merging**
